name: caculator_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/icons/delete.svg
    - assets/icons/add_of_minus_icon.svg
    - assets/icons/divider.svg
    - assets/icons/multi.svg
    - assets/icons/sun.svg
    - assets/icons/moon.svg
