name: caculator_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.14
  flutter_secure_storage: ^8.0.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Light.ttf
          weight: 300
  assets:
    - assets/images/logo.png
    - assets/icons/delete.svg
    - assets/icons/add_of_minus_icon.svg
    - assets/icons/divider.svg
    - assets/icons/multi.svg
    - assets/icons/sun.svg
    - assets/icons/moon.svg
