name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest

    steps:
    # Checkout source code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup Java 17
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Build APK for each flavor
    - name: Build APK for development
      run: flutter build apk --release

    # Upload artifacts (APKs for each flavor)
    - name: Upload APK Artifact for development
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
